### ISSUE TITLE
Pricing attach bug on Chrome

### ISSUE THREAD

**Issue by alexcasalboni** [recurly/recurly-js#139] opened 2014-08-11 10:54 UTC
Here's my case: I'm pre-filling the coupon input (either via html or via JS) and recurly.Pricing doesn't consider it on Google Chrome.

Looking at your code, it looks like [this line](https://github.com/recurly/recurly-js/blob/master/lib/recurly/pricing/attach.js#L48) makes `target('coupon')` return false, as `targetName` is set to `window.event.srcElement`.

It means that [at the first change call](https://github.com/recurly/recurly-js/blob/master/lib/recurly/pricing/attach.js#L42) no additional field gets binded.

It doesn't work even if I set the input value by code (triggering the `change` event).

**Comment by chrissrogers** [comment] 2016-02-11 22:04
Since this hasn't been reproducible, I am going to close this. Please reopen if this comes up again, especially in the new version (v4)

**Closed by chrissrogers** 2016-02-11 22:04 UTC
Labels: bug?
