### ISSUE TITLE
recurly hosted fields not selectable when not at zoom level 100%

### ISSUE THREAD

**Issue by lparry** [recurly/recurly-js#353] opened 2017-06-01 04:22 UTC
> Browser:

chrome

> Steps to reproduce:

- zoom out to 75%
- try and click on a hosted field iframe

> expected behaviour

- field selected and interactable

> actual behaviour

- field masking appears in the correct spot, but clicking the fields has no result. cc number/etc can not be entered

![image](https://cloud.githubusercontent.com/assets/126524/26664515/9cc764dc-46d5-11e7-8293-59178b11d6a8.png)

**Comment by chrissrogers** [comment] 2017-06-01 07:08
I can't reproduce this using our test rig. Do you have a demonstration I can access?

**Comment by lparry** [comment] 2017-06-01 08:55
I don't have anything public that I can point you at just yet as we're still in the process of moving over from another payment service. If you are willing to sign up for an account on our site, I can flip the feature toggle on your account so you can get to the payment form where I am seeing this. Is there an email I can contact you on if you're willing to dig a bit deeper for me?

**Comment by chrissrogers** [comment] 2017-06-01 17:30
GitHub Issues are the best way for me to triage these things. Any code sample that can achieve this would be appreciated. Also happy to do a signup and navigate to your payment form once given access, but it could take a bit longer if going that route.

**Comment by chrissrogers** [comment] 2017-06-07 19:06
I've been unable to reproduce this after a few tries.. I'm thinking it may be related to other style definitions on your page perhaps? I'll close this for now.

**Closed by chrissrogers** 2017-06-07 19:06 UTC
Labels: bug?

**Comment by lparry** [comment] 2017-06-09 05:24
Sorry for the lack of response, I have been quite busy. I'm happy to forget this until we're cut over from our current subscription platform and look at it again later when I can more easily point you at the site
