### ISSUE TITLE
Recurly JS blocked by DuckDuckGo Privacy Essentials

### ISSUE THREAD

**Issue by rborer** [recurly/recurly-js#621] opened 2020-07-13 20:10 UTC
Hi,

Similar to #468 Recurly JS client is blocked by DuckDuckGo Privacy Essentials.

![image](https://user-images.githubusercontent.com/361403/87348681-6f64f200-c555-11ea-9823-6924592127ae.png)

![image](https://user-images.githubusercontent.com/361403/87348690-71c74c00-c555-11ea-897d-6d5e2b82ba77.png)

**Comment by rborer** [comment] 2020-07-13 20:13
In case you wonder, the website in the screenshot is the testing environment of https://paper.li/ . This blocking is sadly preventing some of our users to upgrade to our paid plans...

**Comment by chrissrogers** [comment] 2020-07-13 23:40
Would you mind reporting a broken site through the DuckDuckGo extension? I've had a look through their extension and see that it is loading a list here: https://staticcdn.duckduckgo.com/trackerblocking/v2.1/tds.json

It doesn't appear this list is open source, so seemingly any change will need to be lobbied through DuckDuckGo. In the meantime, I'd suggest a form of detection for cases where `recurly` is unavailable due to any blocking extensions, to request that users disable any extension which may be preventing the page from accepting payments.

We try to keep up with extensions that may be blocking our domains eagerly, and will do so in this case.

**Comment by rborer** [comment] 2020-07-14 07:51
I have already reported the issue through their extension. And tried to contact them on Twitter (with no response so far). I'll update this issue if I receive some feedback from them.

**Comment by hkmaly** [comment] 2020-07-22 20:54
I found this issue when searching by google: https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/457
Maybe creating similar issue for recurly would help? Or is that different extension?

How can I detect if recurly is unavailable due to any blocking extensions? Does it require loading the javascript differently than by putting it in script tag?

**Comment by chrissrogers** [comment] 2020-07-22 21:31
Detection would vary based on the extension. Some may provide a flag or other means of detection, but it would be inconsistent or more likely unavailable. Generally, if `recurly` is unavailable on the page, it would be due to a network issue, which by and large would be caused by a blocking mechanism. This would be the recommended manner of requesting customers disable any blocking mechanism.

The https://github.com/duckduckgo/duckduckgo-privacy-extension extension is indeed the correct repository. thank you for finding that prior request from Square, as it's perfectly related to this issue. I've submitted a request here: https://github.com/duckduckgo/duckduckgo-privacy-extension/issues/471

**Comment by geoffdutton** [comment] 2020-07-22 21:36
@chrissrogers Would I make sense to fall back to a self-hosted version, or do you think there would be a mis-match with the `host-fields.html` (or maybe those are blocked anyway)?

**Comment by chrissrogers** [comment] 2020-07-22 23:01
@geoffdutton I wouldn't recommend self-hosting as a remedy, and it certainly may be that the iframe document would be blocked by the extension either way. My hope is that the issue filed will lead to the duckduckgo tds being updated shortly.

**Comment by rborer** [comment] 2020-07-23 18:51
@chrissrogers @geoffdutton I tested a "self-hosted" version on our testing environment, and although the main JS file is loaded correctly the API & IFrame calls are still blocked. So not a viable option there.

**Comment by chrissrogers** [comment] 2020-12-28 20:06
I'll close this to keep discussion on the following extension issue:

duckduckgo/duckduckgo-privacy-extension#471

Thanks again everyone for your reports and attention on this.

**Closed by chrissrogers** 2020-12-28 20:06 UTC
Labels: question
