### ISSUE TITLE
Validating plan-restricted coupons

### ISSUE THREAD

**Issue by merauluka** [recurly/recurly-js#175] opened 2015-01-26 19:31 UTC
When creating a code that is restricted to certain plans, Recurly.js doesn't appear to be updating the totals correctly when the coupon is set and then the plan is changed. The totals update, but the coupon is applied regardless of the plan restriction.

### Steps to reproduce:

1. Select the plan (we are using radio inputs).
2. Enter the coupon code that works with that plan.
3. Change the plan.

At this point the coupon's discount is applied even though it is restricted to only one plan. I can change the plan to any of our listed subscription plans and it still calculates the discount.

### Inverse issue:

1. Select the plan (one that isn't allowed on the coupon)
2. Enter the coupon code.
3. Change the plan to the one that is allowed on that coupon.

The discount remains at $0 even when the correct plan is chosen. No matter which plan is chosen, the discount remains at $0.

### Coupon settings

Just in case it matters, the coupon we setup has the following options:

1. 25% discount
2. Single use
3. Unlimited redemptions
4. Never expires
5. Only affects one plan (which is annual)

Is this on anyone's radar? Or is there a way to work around it?

**Comment by chrissrogers** [comment] 2015-01-27 04:45
Thank you very much for the super detailed bug report! It made tracking down the issue extremely straightforward.

**Comment by merauluka** [comment] 2015-01-27 17:28
Thank you for responding so quickly! I have been in the position of receiving issue reports that were more like Easter egg hunts than anything else. I figured I save you the troubleshooting time. :-)

So, I cloned the repo, checked out the branch you added, and used the make file to create the combined javascript files. However, I am getting an error one line 1841 of the combined file. It's in the Emitter.prototype.emit function at the line:

```php
Emitter.prototype.emit = function(event){
  this._callbacks = this._callbacks || {};
  var args = [].slice.call(arguments, 1)
    , callbacks = this._callbacks[event];

  if (callbacks) {
    callbacks = callbacks.slice(0);
    for (var i = 0, len = callbacks.length; i < len; ++i) {
      // This is the line that is throwing errors
      callbacks[i].apply(this, args);
    }
  }

  return this;
};
```

The error:

**Uncaught TypeError: Cannot read property 'apply' of undefined**

Do you have any ideas?

**Comment by chrissrogers** [comment] 2015-01-27 20:10
Interesting. That error is quite deep in the pricing. It might help in debugging this to get the circumstance for producing the error, and potentially a stacktrace and dump of the `callbacks` and `args` values when the error occurs.

**Comment by chrissrogers** [comment] 2015-01-27 21:12
I removed a change to an event emitting pattern that was superfluous to the bug changes needed, in the hopes that it might have been causing the issue you were seeing. Any additional detail on the error will still be helpful.

**Comment by merauluka** [comment] 2015-01-27 22:10
### Steps to reproduce

1. Select a plan from a list of radio options.
2. Enter the coupon code.

The error presents when the form tries to recalculate pricing with the coupon code.


### Stack trace

Function | File/Line
--|--
Emitter.emit | (recurly.min.js?nillku:1)
(anonymous function) | (recurly.min.js?nillku:2)
(anonymous function) | (recurly.min.js?nillku:1)
window.(anonymous function) | (recurly.min.js?nillku:1)
(anonymous function) | (test3?plan=prof…MIjPWy&call…:1)

### Scope Variables


![variables](http://files.clikbox.com/skitch/Research_Membership_USD_%241197_year_%7C_Demand_Metric-20150127-150818.jpg)
![variables 2](http://files.clikbox.com/skitch/Research_Membership_USD_%241197_year_%7C_Demand_Metric-20150127-150935.jpg)

**Comment by chrissrogers** [comment] 2015-01-27 22:13
Awesome, thank you. I'll dig into this.

**Comment by merauluka** [comment] 2015-01-27 22:21
After looking a the stacktrace I realized it was obnoxiously unhelpful. Here's a more helpful version.

### A More Helpful Stack Trace

I switched from the minified file so the results are more meaningful.

Function | File/Line | Line Text
-------|------- | -------
Emitter.emit | (recurly.js?nillku:1841) | `callbacks[i].apply(this, args);`
(anonymous function) | (recurly.js?nillku:3919) | `self.emit('set.coupon', coupon);`
(anonymous function) | (recurly.js?nillku:332) | `done(errors('api-error', res.error));`
window.(anonymous function) | (recurly.js?nillku:833) | `if (fn) fn(null, data);`
(anonymous function) | (test?plan=profe…jPWy&callba…:1) | `__jp2({"error":{"code":"not-found","message":"Couldn't find Coupon with coupon_code = test"}})`

**Comment by chrissrogers** [comment] 2015-01-27 22:28
From the trace, it looks like you might be listening to the 'set.coupon' event without specifying a listener. I can reproduce this error with the following snippet:

```js
pricing.on('set.coupon');
```

When we should have a listener to handle the event being emitted:

```js
pricing.on('set.coupon', function (coupon) {
  console.log(coupon);
});
```

**Comment by merauluka** [comment] 2015-01-27 22:42
Magic! Fixed it. Thank you very much.

**Comment by merauluka** [comment] 2015-01-28 20:49
Hello Chris,

I'm sorry to continue on this, but I believe I may have found another issue.

Everything is calculating correctly. We can select a plan, enter a coupon code, and change the plan and the calculations are performed properly. Specifically, coupons that are restricted to a certain plan are validated before they are applied. Good stuff.

However, if you delete the coupon code, the price isn't recalculated until either a different coupon code is entered or the plan is changed.

-Melissa

**Comment by chrissrogers** [comment] 2015-01-28 22:03
@merauluka thanks for pointing that out! I've pushed a fix to the PR. I hope to get some tests in within the next few days so we can have some real coverage here. Your poking at it has been extremely helpful.

**Comment by merauluka** [comment] 2015-02-02 17:04
Do we have an update on this issue?

**Comment by chrissrogers** [comment] 2015-02-02 19:15
I expect we'll have this fix merged in and deployed in a new version by the end of the week.

**Comment by merauluka** [comment] 2015-02-02 20:27
Thanks Chris!

**Comment by bhelx** [comment] 2015-02-14 03:45
Update: I'm just reviewing this code. Should merge it this tonight or this weekend.

**Closed** 2015-02-15 14:09 UTC
Labels: confirmed bug

**Comment by bhelx** [comment] 2015-02-15 14:10
@merauluka sorry for the delay. It's merged.
