### ISSUE TITLE
After several times quickly open and close dialog with form, recurly fields are invisible

### ISSUE THREAD

**Issue by roman-mateush** [recurly/recurly-js#337] opened 2017-03-09 15:07 UTC
Hi, after several times quickly open and close dialog with form, recurly fields are invisible. Looks like that happens race condition for `readyState`. When fields are visible `readyState` is 2, but if invisible `readyState` is 1. Invisible fields stay until the refresh page

**Comment by chrissrogers** [comment] 2017-03-09 17:55
Do you have a demo of this in effect? I'd like to have a look at the case. At first glance, I recommend preventing the dialogue form closing until the fields are ready. Use the `recurly.ready` function with a callback to know when everything has been loaded.

**Closed** 2017-03-16 15:45 UTC

**Comment by thgreasi** [comment] 2017-06-23 05:49
This also affected me. Also `.ready()` doesn't seem to be documented (but that's fine with me).
Hosted the billing info form inside a angularjs ui-bootstrap dialog, which creates the DOM when opened and destroys it when closing.

I also have a radio to change the form between credit card & bank account mode, where after every change I call `configure()` again to make it work. My question regarding this is whether I should also wait `recurly.ready()` before each call of `configure()`?

**Comment by chrissrogers** [comment] 2017-06-23 13:26
Yes, you should wait for ready before reconfiguring

**Comment by crpahl** [comment] 2018-08-02 20:39
We have a similar situation where our form is inside of a dialog and closing it during initialization gets it into an awkward state. It would be really nice if the recurly.ready function was documented as a supported option if that's still the case 😃  We were only able to find this after looking through the source and weren't sure if this would be supported going forward until coming across this closed issue.

Our issue specifically is caused by closing our dialog window immediately after opening it. This causes the recurly.readState to equal 1. As a result the next call to recurly won't reconfigure the hosted fields due to this conditional:

```
if (this.readyState > 1 && !this.hostedFields.integrityCheck(this.config.fields)) reset = true;
```

Would it be possible to allow it to reset if it's currently stuck in readyState = 1? Preventing the window from closing by using the recurly.ready function worked for us, but it would be nice if it was able to reconfigure itself when it ends up in this state as well.
