### ISSUE TITLE
Firefox: Credit card details can't be pasted into hosted fields

### ISSUE THREAD

**Issue by ellotheth** [recurly/recurly-js#432] opened 2018-03-09 09:14 UTC
In Firefox using the `card` iframe, the keyboard shortcut for pasting (i.e. `ctrl+v`) does not paste anything into the hosted fields. Pasting with the context menu works, and both methods seem to work in Chrome.

**Comment by chrissrogers** [comment] 2018-03-14 16:17
Thanks for the report. I'll do a little testing and see what might be causing the restriction. What Firefox version are you using?

**Comment by chrissrogers** [comment] 2018-03-14 16:19
Noting that I can reproduce this behavior in `58.0.2` and `59.0`

**Comment by ellotheth** [comment] 2018-03-14 16:23
I was using `59b<something>` when I reported it, and I'm now on `60.0b2`.

**Comment by chrissrogers** [comment] 2018-03-14 17:36
Looks like this is related to https://github.com/jessepollak/payment/issues/79

I've verified that that the PR mentioned in that issue does fix the issue in FireFox. It seems like Chrome treats system clipboard commands differently, and doesn't trigger the keyboard event that `restrictNumeric` listens on, thus it's unaffected.

Here is the relevant change needed: https://github.com/jessepollak/payment/pull/86/files#diff-aab7b1abbbb85544dd4e324961d88e7dR381

**Comment by chrissrogers** [comment] 2018-03-21 00:18
FYI I've gone ahead and forked the dependency, incorporating the fix referenced above. This will be incorporated into our hosted codebase soon. Once it is deployed I'll post an update here

https://github.com/chrissrogers/payment/releases/tag/v2.3.0-patch-01

**Closed** 2018-03-23 20:27 UTC
Labels: bug, dependency

**Comment by chrissrogers** [comment] 2018-03-23 20:29
This was closed because we are preparing the hosted codebase for release. I'll put an update here once it's deployed
