### ISSUE TITLE
Recurly js hosted field  iframe style visibility set to hidden

### ISSUE THREAD

**Issue by denomon** [recurly/recurly-js#298] opened 2016-10-03 22:38 UTC
I have noticed on some browsers my recurly iframes load but are hidden as shown in my iframe snippet below.
<body>
<input id="recurly-hosted-field-input" style="visibility: hidden; color: black; .....

It works fine on chrome. Firefox and IE are having this issue on pc/laptop.
Firefox in iphone 5s works fine btw.

What could be the issue?
Im using recurly js V4

**Comment by chrissrogers** [comment] 2016-10-03 22:56
The fields load initially hidden then unhide once the complete initialization. This indicates that something has gone wrong during init. Are you seeing any error messages in the browser console?

**Comment by denomon** [comment] 2016-10-03 23:35
@chrissrogers  No error messages on console.

**Comment by denomon** [comment] 2016-10-04 11:44
@chrissrogers  Error thrown on firefox is as below.
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create hosted-field.js:4:19864
Any advice?

**Comment by chrissrogers** [comment] 2016-10-04 16:21
Looks like it's just a warning from Firefox, nothing that would halt the init. Can you give me the exact browser versions and platforms?

**Comment by denomon** [comment] 2016-10-04 18:59
I looked further into your first suggestion and yes it was an issue with completing initialization.Im using vue js on laravel blade.  Currently Recurly config is initialised  after vue js is has rendered the DOM. 

initialising  it before vue js is ready seems to solve the problem in firefox and IE. But im thinking  it might fail if the DOM is not ready due to  initialising recurly before vue js has rendered the DOM?

**Comment by chrissrogers** [comment] 2016-10-04 19:12
I definitely recommend initializing recurly.js after the dom is ready, if possible.

**Comment by denomon** [comment] 2016-10-05 12:15
My colleague has posted the question here as we still unable to init recurly after Vue js is ready. https://stackoverflow.com/questions/39872470/recurly-js-checkout-not-working-in-firefox-when-in-a-vue-js-component

**Comment by chrissrogers** [comment] 2016-11-02 23:32
@denomon are you still experiencing issues?

**Comment by carlosantoniodasilva** [comment] 2016-11-04 13:29
@chrissrogers we have some users reporting that the fields are not loading, preventing them from subscribing to our service. 

We don't use vue or any other similar library for our subscription page, the `recurly.configure` call is triggered on a jquery ready event at the moment.

I'm trying to gather more information with a couple users, specially if any errors are being triggered - just wanted to give you a heads up on that. I'll keep you posted.

**Comment by chrissrogers** [comment] 2016-11-04 16:22
Thanks @carlosantoniodasilva. You may wish to use a reporting service like bugsnag to collect any and all errors that occur, in order to collect as much information as possible.

**Comment by carlosantoniodasilva** [comment] 2016-11-16 11:22
@chrissrogers I confirmed that what we're seeing is a different scenario: some users living in different countries are being blocked, preventing recurly.js from loading, causing the form to break / fields not to load.

I've sent a couple questions through support, we can continue the conversation there. Thanks!

**Comment by chrissrogers** [comment] 2016-11-16 16:34
Thank you @carlosantoniodasilva -- closing this to resolve amongst ourselves and technical operations.

**Closed by chrissrogers** 2016-11-16 16:34 UTC
