### ISSUE TITLE
Safari Autofill does not seem to propagate Recurly change event state properly

### ISSUE THREAD

**Issue by carlosantoniodasilva** [recurly/recurly-js#561] opened 2019-10-24 14:39 UTC
We seem to be having an issue with recent Safari versions, when users try to use Autofill Recurly doesn't seem to be emitting the "change" event properly.

Here's the event information we're getting right after autofill is triggered, filling in the card number, expiration month and year:
 
![Screen Shot 2019-10-24 at 11 27 24](https://user-images.githubusercontent.com/26328/67495950-0b5e6e80-f652-11e9-892e-e7b7c429b1d7.png)

This is the event we get back after we focus on the year field:

![Screen Shot 2019-10-24 at 11 26 22](https://user-images.githubusercontent.com/26328/67495947-0b5e6e80-f652-11e9-87c6-645e87cafb1e.png)

As you can see, the first emitted event does not report the month/year field as present, which we'd expect since those fields were autofilled, and so as we receive them marked as "empty" it causes our form to prevent the submission. (the button is kept disabled.)

The same behavior appears to be working on Chrome as far as I could test. Let me know if we can help with providing any other information to help reproduce and hopefully fix the issue. Thanks.

**Comment by chrissrogers** [comment] 2019-10-24 21:18
Hi @carlosantoniodasilva -- thanks for the really helpful detail here! Just a couple questions to cover all of the bases.

Just so I can confirm the issue: In Safari, the change event is reliably being emitted following the autofill action, but the state object emitted by the change event does not contain the updated state?

And some follow-ups
1. Are you using the combined card field, or the distinct card fields (separate number, expiry, and cvv)?
2. when autofilling in Safari, are the fields being updated?

**Comment by carlosantoniodasilva** [comment] 2019-10-25 13:12
@chrissrogers 

>  In Safari, the change event is reliably being emitted following the autofill action, but the state object emitted by the change event does not contain the updated state?

Yes, the events appear to be emitted, but they don't correspond to the actual values for the expiration month/year.

> Are you using the combined card field, or the distinct card fields (separate number, expiry, and cvv)?

Distinct card fields: number/month/year/cvv

> when autofilling in Safari, are the fields being updated?

Yes, they are.

---

Here's a GIF of the behavior I'm seeing in the app, sorry I should've included it with the original report:

![recurly](https://user-images.githubusercontent.com/26328/67573817-9baeb900-f70f-11e9-9ca5-ef20cf59f84e.gif)

We track the change event on each field to determine when all of them have at least something filled in, to enable the submission of the form. In the case above, the expiration month/year don't report as having a value in the state we get back (they come as empty), until we focus on the year.

**Comment by chrissrogers** [comment] 2019-10-25 22:03
Perfect! I have a handle on this issue now and am looking at potential workarounds that we can implement. It appears Safari's event timing is too early for field state to have been updated. I'll update here when I have a better explanation.

**Comment by chrissrogers** [comment] 2019-10-25 23:20
An update: I've identified and built a fix for this. The fix will go through review and validations, and should make it into our next release of the internal library that manages hosted fields. This issue will close when that change is confirmed to go into the release, and I'll update here when I have a good timeline for you. Cheers!

**Comment by chrissrogers** [comment] 2019-10-25 23:22
To give some insight into the issue: Safari does not send `focus` events along with the `HTMLElement#focus` method call, as many other browsers do. So some of the state management routines we employ simply weren't firing when the change originated from autofill.

**Comment by carlosantoniodasilva** [comment] 2019-10-28 13:47
Thanks @chrissrogers, I appreciate you quickly looking into it and working on a fix, and also the extra details about the issue. Will keep an eye on for the issue being closed here to follow-up internally.

**Closed** 2019-10-28 17:39 UTC
Labels: bug?

**Comment by carlosantoniodasilva** [comment] 2019-11-04 17:41
@chrissrogers @dbrudner I just tested this one again and it appears to be working great now, thanks for the fix.

Just out of curiosity: was there a change in this repo, or somewhere else publicly, that I could look at? I didn't find anything on a quick search. :)

**Comment by chrissrogers** [comment] 2019-11-04 18:59
@carlosantoniodasilva -- great to hear, thank you for confirming on your end!

The change itself was made to one of our internal libraries responsible for rendering hosted fields, so no code change was necessary to Recurly.js itself. The best I can do is just refer to the browser issue itself :)

**Comment by carlosantoniodasilva** [comment] 2019-11-04 21:12
@chrissrogers alright, just trying to kill my outsider dev curiosity here ;), thanks again!

**Comment by chrissrogers** [comment] 2019-11-04 22:20
Really what it comes down to is forcing the `focus` event to occur in all environments by simply creating a native `focus` [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event) and then propagating that out.

When autofill occurs, the values given by the browser are assigned out to the various fields manually, and then we programmatically move focus to those fields and back to the number field. We do this to get around a bug in some versions of Safari for iOS that don't clear the placeholder when a value is assigned programatically. The focus event itself is also what triggers state update in those fields. So since the focus events weren't calling state update handlers in Safari, the state wasn't being updated. All for developer curiosity!

**Comment by carlosantoniodasilva** [comment] 2019-11-05 01:01
Cool :+1:, appreciate the details @chrissrogers!
